### ISSUE TITLE
Create a CONTRIBUTE.md in main folder file to help absolute beginners with contributing in this repo

### ISSUE THREAD

**Issue by MitanshiKshatriya** [IEEE-WIE-VIT/Awesome-DSA#13]

**Comment by twozero88** [comment]
Explaining the github process in general right?

**Comment by MitanshiKshatriya** [comment]
We already had a submission for CONTRIBUTING.md. You can contribute by adding data structures or algorithms to the repository. 
We really look forward to your contribution to this repository.
