### ISSUE TITLE
Create the topic folders separately

### ISSUE THREAD

**Issue by MananOO12** [IEEE-WIE-VIT/Awesome-DSA#28]
Create each topic folder separately and inside those folders create language wise folders.
For eg.
Data_Structures/Array/C
Data_Structures/Array/Python
...
 It would be eaiser to look for a topic if we move the programs in existing folders to the respective folders topicwise.

**Comment by MitanshiKshatriya** [comment]
Hi! Thanks for the suggestion.

Keeping your suggestion in mind and to avoid unnecessary work, we will change the directory paths for data structures in this way -- 
lang/data structures/name_of_the_ds/files related to it                                                                                                                                       README.md and CONTRIBUTE.md would be updated to reflect the same.
